add `global_const` rendering
andrewrk/autodoc pull request #6
Opened 2024-03-05 10:18 UTC by Rexicon226

2024-03-05 10:22 UTC, Rexicon226 commented on lib/main.js
> +        resizeDomList(domListErrSets, members.length, '<li><a href="#"></a></li>');
I think this is the right html signature? Please correct me.

2024-03-05 16:33 UTC, alichraghi commented on lib/main.js
> +        resizeDomList(domListErrSets, members.length, '<li><a href="#"></a></li>');
`<a>` in `<li>`? yes that's correct

2024-03-05 21:19 UTC, andrewrk commented
[here's a page to compare it to](https://ziglang.org/documentation/master/std/#A;std:fs.MAX_PATH_BYTES)

2024-03-05 21:26 UTC, Rexicon226 commented
> [here's a page to compare it to](https://ziglang.org/documentation/master/std/#A;std:fs.MAX_PATH_BYTES)

I see. So we should insert the docstring in the view as well. Can do now!

2024-03-05 21:31 UTC, Rexicon226 commented
@andrewrk Should the docstring be above or below the source? I personally think it should be above, but your choice.

2024-03-05 21:31 UTC, andrewrk commented
Exercise taste! Show me your vision :)

2024-03-05 21:42 UTC, Rexicon226 commented
My computer clock once again decided that it is yesterday, but I pushed!
![image](https://github.com/andrewrk/autodoc/assets/87927264/821eb833-2f6d-4b79-b593-6019104b75c5)

2024-03-05 21:54 UTC, andrewrk commented
Can I see a screenshot of the error set page?

[comparison](https://ziglang.org/documentation/0.9.0/std/#std;event.Loop.Request.Msg.OpenAt.Error)

[note that current autodocs is regressed from this](https://ziglang.org/documentation/master/std/#A;std:posix.OpenError)

2024-03-05 22:02 UTC, Rexicon226 commented
It's currently in the middle of those two 😄 
I can instead of just rendering source, parse them like in the 0.9 docs. Give me a like 20 minutes to get home from school.
![image](https://github.com/andrewrk/autodoc/assets/87927264/d82be6ad-f9de-4e42-bb73-ef3ed3dbe90e)

2024-03-06 06:43 UTC, Rexicon226 commented
*Now* error sets work :)
Docstrings are a TODO, as I need to figure out how to best way to do them. Expect a follow up tomorrow. I think I've gotten over the Dunning-Kruger hill now, but time will tell.

![image](https://github.com/andrewrk/autodoc/assets/87927264/02627ced-fdd3-411a-8219-a85b2c83ce46)

2024-03-06 07:06 UTC, Rexicon226 commented
I've actually realized docstrings aren't that hard. Will push in a bit.

2024-03-06 07:24 UTC, andrewrk requested changes

2024-03-06 07:24 UTC, andrewrk commented on lib/index.html
> +    </div>
The section is already above, line 313

2024-03-06 07:27 UTC, andrewrk commented
previous error set implementation: https://github.com/andrewrk/autodoc/blob/a56d2c180084a065b12660d63cf0e88d502800d4/lib/main.js#L528-L560

2024-03-06 07:29 UTC, Rexicon226 commented
Sorry @andrewrk, I tabbed back to this GitHub page only once I had pushed. I didn't see you reviewing. I just cleaned it up a bit and added doc strings. I'm terrible at naming so please suggest fixes there as well :)

2024-03-06 07:29 UTC, Rexicon226 commented on lib/index.html
> +    </div>
See it!

2024-03-06 07:38 UTC, andrewrk commented
can you limit the PR to one enhancement? let's start with the const view, yeah?

2024-03-06 07:41 UTC, Rexicon226 commented
Gotcha. Apologies for being all over the place today :) I feel this PR has gotten very noisy and it's all my fault. Would you like me to close this and open two new ones for each feature? (global const and error set)?

2024-03-06 08:20 UTC, closed without merging